In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data=pd.read_csv("cars.csv")
data

enginesize  carlength  carwidth  carheight  price
0          130      168.8      64.1       48.8  13495
1          130      168.8      64.1       48.8  16500
2          152      171.2      65.5       52.4  16500
3          109      176.6      66.2       54.3  13950
4          136      176.6      66.4       54.3  17450
..         ...        ...       ...        ...    ...
94          97      165.3      63.8       54.5   7299
95          97      165.6      63.8       53.3   7799
96          97      165.3      63.8       54.5   7499
97          97      170.2      63.8       53.5   7999
98          97      162.4      63.8       53.3   8249

[99 rows x 5 columns]

In [14]:
# data.insert(0, 'Ones', 1)
cols = data.shape[1]
X = data.iloc[:,0:cols-1].values
y = data.iloc[:,cols-1:cols].values
print("The values of x = ")
print(X)

print("The values of y = ")
print(y)

The values of x = 
[[130.  168.8  64.1  48.8]
 [130.  168.8  64.1  48.8]
 [152.  171.2  65.5  52.4]
 [109.  176.6  66.2  54.3]
 [136.  176.6  66.4  54.3]
 [136.  177.3  66.3  53.1]
 [136.  192.7  71.4  55.7]
 [136.  192.7  71.4  55.7]
 [131.  192.7  71.4  55.9]
 [131.  178.2  67.9  52. ]
 [108.  176.8  64.8  54.3]
 [108.  176.8  64.8  54.3]
 [164.  176.8  64.8  54.3]
 [164.  176.8  64.8  54.3]
 [164.  189.   66.9  55.7]
 [209.  189.   66.9  55.7]
 [209.  193.8  67.9  53.7]
 [209.  197.   70.9  56.3]
 [ 61.  141.1  60.3  53.2]
 [ 90.  155.9  63.6  52. ]
 [ 90.  158.8  63.6  52. ]
 [ 90.  157.3  63.8  50.8]
 [ 90.  157.3  63.8  50.8]
 [ 98.  157.3  63.8  50.8]
 [ 90.  157.3  63.8  50.6]
 [ 90.  157.3  63.8  50.6]
 [ 90.  157.3  63.8  50.6]
 [ 98.  157.3  63.8  50.6]
 [122.  174.6  64.6  59.8]
 [156.  173.2  66.3  50.2]
 [ 92.  144.6  63.9  50.8]
 [ 92.  144.6  63.9  50.8]
 [ 79.  150.   64.   52.6]
 [ 92.  150.   64.   52.6]
 [ 92.  150.   64.   52.6]
 [ 92.  163.4  64.   54.5]
 [ 92.  1

In [8]:
class LinearRegression:
    
    def __init__(self, l_rate=0.001, iterations=1000):  #assign values for hyper-parameters
        self.l_rate = l_rate  #learning rate
        self.iterations = iterations  #number of iterations

    def fitGD(self, x, y):  #Fit the training data using Gradient Descent
        self.cost = []  # An empty list to store the error in each iteration
        self.theta = np.zeros((1 + x.shape[1]))  #intitalization,,,Array of zeros , shape= columns + 1  (3,1)
        n = x.shape[0]  #number of training examples 99
        
        for i in range(self.iterations):
            y_pred = self.theta[0] + np.dot(x, self.theta[1:])  # hypothesis h(x).. x=(99,2), theta[1:]=(2,1)
            mse = (1/n) * np.sum((y_pred - y)**2)  #compute the cost function J(theta) using mse
            self.cost.append(mse)  #tracking 
            
            #Derivatives
            d_theta1 = (2/n) * np.dot(x.T, (y_pred - y)) # x.T=(2,99)... (y_pred - y)=(99,1)
            d_theta0 = (2/n) * np.sum(y_pred - y)
            
            #Values update
            self.theta[1:] = self.theta[1:] - self.l_rate * d_theta1
            self.theta[0] = self.theta[0] - self.l_rate * d_theta0                       
        return self
    
    
    def predictGD(self, x):  #Predicts the value after the model has been trained/Gradient Descent.
        return self.theta[0] + np.dot(x, self.theta[1:])
    
    
    def fitNQ(self,x, y):  #Fit the training data using Normal Equation
        z = np.ones((x.shape[0],1))  #Array of ones , shape= rows, one cloumn (99,1)
        x = np.append(z, x, axis=1)  #Array, its 1st cloumn contains ones, other columns contains features x (99,3)
        self.thetas = np.linalg.pinv(x.T.dot(x)).dot(x.T).dot(y) # normal equation,, use pinv() in case of non invertible matrix
  
        return self   

    def predictNQ(self, x):  #Predicts the value after the model has been trained/Normal Equation.
        z = np.ones((x.shape[0],1))  #Array of ones , shape= rows, one cloumn (99,1)
        x = np.append(z, x, axis=1)  #Array, its 1st cloumn contains ones, other columns contains features x (99,3)
        return np.dot(x, self.thetas)  #Linear equation

In [10]:
#features scaling using z-score
def scale(x):
    x_scaled = x - np.mean(x, axis=0)
    x_scaled = x_scaled / np.std(x_scaled, axis=0)
    return x_scaled

In [12]:
x_sd= scale(x)  #call the function scale()

lr = LinearRegression()  # creating object lr using the class LinearRegression()
lr.fitGD(x_sd, y)  #call the method fitGD()
lr.fitNQ(x, y)  #call the method fitNQ()

In [28]:
# print theta 0, 1, 2
print("theta_0= ", lr.theta[0])
print("theta_1= ", lr.theta[1])
print("theta_2= ", lr.theta[2])

theta_0=  12007.838077818737
theta_1=  7378.449674762259
theta_2=  1208.9169319699492


In [30]:
# print theta 0, 1, 2
print("theta_0= ", lr.thetas[0])
print("theta_1= ", lr.thetas[1])
print("theta_2= ", lr.thetas[2])

theta_0=  -25593.799257663304
theta_1=  165.83734503865804
theta_2=  346.6014627961735


In [32]:
y_pred = lr.predictGD(x_sd) #predict training examples using Gradient Descent.
y_predNQ = lr.predictNQ(x)  #predict training examples using Normal Equation.

In [34]:
#Evaluate Training GDModel using adjusted R squared
errors = np.sum((y_pred - y)**2)
sst = np.sum((y - np.mean(y))**2)
r2_GD = 1 - (errors/sst)

adusted_r2_GD= 1-((1-r2_GD) * (x.shape[0] -1)/(x.shape[0] - x.shape[1] - 1))
print (adusted_r2_GD)

0.7833948201180297


In [36]:
#Evaluate Training NQModel using adjusted R squared
errors = np.sum((y_predNQ - y)**2)
sst = np.sum((y - np.mean(y))**2)
r2_NQ = 1 - (errors/sst)

adusted_r2_NQ= 1-((1-r2_NQ) * (x.shape[0] -1)/(x.shape[0] - x.shape[1] - 1))
print (adusted_r2_NQ)

0.838274550825138
